### ISSUE TITLE
 I could not find the usage of AUTOSPLOIT_TERM_OPTS

### ISSUE THREAD

**Issue by wangay** [NullArray/AutoSploit#1072]
hello,I run it with code . but there are no " 1: "usage and legal" "like this to show out.

and I could not find the usage of AUTOSPLOIT_TERM_OPTS

is there something wrong?

===
mac os

**Comment by Ekultek** [comment]
Did you try typing help?

**Comment by Ekultek** [comment]
@wangay ping?

**Comment by wangay** [comment]
> Did you try typing help?


`1. 'default_modules'
2. 'default_fuzzers'
root@autosploit# 1
[+] attempting to load API keys
[+] Shodan API token loaded from ~/Documents/git/AutoSploit/etc/tokens/shodan.key
[+] Censys API token loaded from ~/Documents/git/AutoSploit/etc/tokens/censys.key
[-] no arguments have been parsed at run time, dropping into terminal session. to get help type `help` to quit type `exit/quit` to get help on a specific command type `command help`
root@autosploit# exit`



that's to say :  there is no 1~9 usage desc.

**Comment by Ekultek** [comment]
So no you didn’t try typing help?

**Comment by Ekultek** [comment]
I don’t understand what’s so hard to understand about a “terminal”

**Comment by Ekultek** [comment]
So if you can’t figure out how to use a terminal you probably shouldn’t be using this tool
