### ISSUE TITLE
[Request] Compatibility with Parrot Security OS

### ISSUE THREAD

**Issue by PaganGuy** [NullArray/AutoSploit#1081]
No errors, I have a request I would VERY much like to see happen and it would take very little to achieve on your end. PLEASE make this compatible with Parrot Security OS.

Parrot is modeled from Kali and based on Debian so this should be an easy task. Thanks for your time & efforts!

**Comment by Ekultek** [comment]
Parrot is debian as you said, this should already be compatible without any changes.
