### ISSUE TITLE
Asking for Curses Module

### ISSUE THREAD

**Issue by mmorga28** [NullArray/AutoSploit#11]
When I try to run the: python autosploit.py install 
I get this message:

$ python autosploit.py install
Traceback (most recent call last):
  File "autosploit.py", line 8, in <module>
    from blessings import Terminal
  File "C:\Python27\lib\site-packages\blessings\__init__.py", line 5, in <module                              >
    import curses
  File "C:\Python27\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

**Comment by gafoo** [comment]
When you try to google this problem - what message you get?

**Comment by JannisKirschner** [comment]
I suppose you use windows, the curses module is not supported on windows machines.
You can try and install an unofficial windows binary from here:
 https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses

**Comment by NullArray** [comment]
Yep i would recommend trying @JannisKirschner fix.  I might just switch to using ANSI coloring in the future. I think that should be supported on Windows as well.
