### ISSUE TITLE
Traceback issue 

### ISSUE THREAD

**Issue by djaffarou** [NullArray/AutoSploit#114]
I have clone AutoSploit on termux (Android nougat 7.0) ; the clone have been successful but when I put 
python autosploit.py
and I press enter it lauch a while and show me 3 bugs:
file /data/data/com.termux/files/home/AutoSploit/autosploit.py line 10 main in <module>

file /data/data/com.termux/files/home/AutoSploit/lib/autoput.py raw_input (NameError :raw_input not defined)

file /data/data/com.termux/files/home/AutoSploit/main.py choice = prompt("it appears that service {} is not enabled, would you like us to enable it for you[y/N]")

**Comment by Ekultek** [comment]
You need to run it with python 2.x you’re running with python 3.x
