### ISSUE TITLE
Wont start apache service

### ISSUE THREAD

**Issue by cmcjacob** [NullArray/AutoSploit#138]
+] welcome to autosploit, give us a little bit while we configure
[i] checking your running platform
[i] checking for disabled services
[?] it appears that service Apache2 is not enabled, would you like us to enable it for you[y/N]: y
[+] Executing command '/home/cmc/Desktop/Scripts/AutoSploit/etc/scripts/start_services.sh linux'
[+] services started successfully
[?] it appears that service Apache2 is not enabled, would you like us to enable it for you[y/N]: y

I already have Apache installed, it's not detecting it. (latest version)
Also have latest version of Python installed. Arch Linux

I was able to fix this problem by editing main.py, in the services check I changed 'apache2' to 'apache' and it detected the service. **Arch Linux uses plain apache as service name, not apache2**

**Comment by Ekultek** [comment]
Autosploit was built on Debian, there’s still kinks in it for other distros, thank you for bringing that to our attention

**Comment by Ekultek** [comment]
Also you just have edited more than just the `apache2` name. As far as I’m aware you can’t call services with `sudo service` on arch?

**Comment by cmcjacob** [comment]
It didn't show any errors when it was trying to before I removed the check,
but I already had it started.  This is the correct way for arch:

sudo systemctl start apache

**Comment by Ekultek** [comment]
I just changed it as systemctl by default. Most linux systems should have that in their system so it should work on Debian and Arch now, via https://github.com/NullArray/AutoSploit/commit/b998ad8b26ed10b8bd8b095241a808b111ffa574
