### ISSUE TITLE
Can't terminate script

### ISSUE THREAD

**Issue by cmcjacob** [NullArray/AutoSploit#140]
When scanning shodan, and attempting to abort the script, it is impossible using CTRL+C to terminate.  Have to manually kill the task from manager.

**Comment by Ekultek** [comment]
Elaborate a little more please?

**Comment by cmcjacob** [comment]
I was using python3, that was probably the problem.  The script hung while scanning shodan and it had to be forcefully terminated because the timer that capitalizes each letter wouldn't stop. Closing as this doesn't occur with python2.
