### ISSUE TITLE
load the module failed!

### ISSUE THREAD

**Issue by ccpickyou** [NullArray/AutoSploit#144]
I was unable to load the module when I set it up for an attack.
![default](https://user-images.githubusercontent.com/41933286/43434846-0283d00c-94b0-11e8-8068-a05498e21ecf.PNG)

**Comment by Ekultek** [comment]
Are these personal modules?

**Comment by ccpickyou** [comment]
The name of the module is the IP address, which is not found in the file. I don't know why this module should be loaded like this.

**Comment by ccpickyou** [comment]
i get it!

**Comment by ccpickyou** [comment]
thanks you

**Comment by ccpickyou** [comment]
Thank you
