### ISSUE TITLE
error invalid api key

### ISSUE THREAD

**Issue by killercoderz4** [NullArray/AutoSploit#16]
good day.i successfully setup the tool an installed all dependencies smoothly.i also registered in shodan and collected my api key. when i put the api key ,it registers ok. when i select option 2 gather, it generates this error  [!]Critical. An error was raised with the following error message.

Invalid API key
. any solutions.thanks

**Comment by ashishchakrabortty** [comment]
I am facing the same issue. Not able to gather any host information because of invalid API key.
Kindly assist.

**Comment by NullArray** [comment]
Hi, please make sure that when you enter your API key you don't have any erroneous spaces or apostrophes in it, or anything like that. To have autosploit prompt you to input a new key delete the `api.p` file and restart the script. Simply copy and paste the key exactly as it is provided by Shodan.

**Comment by killercoderz4** [comment]
i did exactly that.copy and paste.do i need a subscription from shodan for it to work. ijust registered .it generated a key . i copy and pasted it in the terminal .on gather option it says invalid key

**Comment by killercoderz4** [comment]
i did exactly that.copy and paste.do i need a subscription from shodan for it to work. ijust registered .it generated a key . i copy and pasted it in the terminal .on gather option it says invalid key

**Comment by closethe** [comment]
before u paste API from Shodan ,make sure it doesn't have any spaces,and it not need subscription.

**Comment by ashishchakrabortty** [comment]
Hello,
the api.p file has the key in the following format:
S'API KEY'
p0

Is this correct? I made sure there were no spaces while pasting the API key.

**Comment by NullArray** [comment]
Glad it was solved and the only documentation there is for now is the readme file.
