### ISSUE TITLE
Unable to connect to Shodan

### ISSUE THREAD

**Issue by getsecnow** [NullArray/AutoSploit#18]
i get this error when i run autosploit 

[+]Please stand by while results are being collected...

From cffi callback <function _verify_callback at 0x7fd71e69cb90>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'

[!]Critical. An error was raised with the following error message.

**Comment by Robvred** [comment]
You'll need to upgrade your cryptography pin

**Comment by NullArray** [comment]
Latest version tries to resolve the issue like so:

```
@retry(stop_max_attempt_number=3)
def try_shodan():
    try:
        api = shodan.Shodan(SHODAN_API_KEY)
    except Exception as e:
        print("\n[{}]Critical. API setup failed: {}\n".format(t.red("!"), e))
        # sys.exit(e)
    return api
```

I can't remember the number of the Pull Request that added this but this should help with your problem. Since, if the program fails to connect to Shodan it will retry a couple of times.

**Comment by NullArray** [comment]
Oh yeah forgot to mention, there was an issue similar to this one that didn't have the SSL lib error included that i kind of mixed up with this one. But you should update your python libraries as well. Just run:

`sudo apt-get update && sudo apt-get upgrade`

Or your distro's equivalent.
