### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by isaacmuchunu** [NullArray/AutoSploit#22]
Am getting this after "python autosploit.py"

 File "autosploit.py", line 24
    print t.cyan("""
          ^
SyntaxError: invalid syntax

**Comment by closethe** [comment]
make sure ur python version is 2.7

**Comment by NullArray** [comment]
Hey, sorry about that. After the latest Pull Request was merged the indentation for that line was off. 

I've fixed.

https://github.com/NullArray/AutoSploit/commit/b07971f815b1fe1f7861e6c6f24cb96d5ad1313c

**Comment by slick5555** [comment]
I have a similar error but its a tad different ...
python ./autosploit.py
  File "./autosploit.py", line 27
    print t.cyan("""
          ^
SyntaxError: invalid syntax

**Comment by slick5555** [comment]
Im getting this error 
python ./autosploit.py
  File "./autosploit.py", line 27
    print t.cyan("""
          ^
SyntaxError: invalid syntax

**Comment by Ekultek** [comment]
Which branch? And did you run python2?

- Thomas Perkins

**Comment by Ekultek** [comment]
`python2 autosploit.py`
