### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [NullArray/AutoSploit#346]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by Ekultek** [comment]
What would the significance of an appimage be? It seems that would be more of a binary release then something added to the repository

**Comment by zero77** [comment]
@Ekultek 
> It seems that would be more of a binary release then something added to the repository

Yes, i think so, should i have posted this somewhere else.

**Comment by Ekultek** [comment]
No you posted it in the correct location. But what isnthe significance of an appimage when you can just git clone it? Just trying to understand why you want it

**Comment by zero77** [comment]
Ok i see, well:

To use it you don't need root or any dependencies that i know of, all you need is wget, curl and chmod +x and ./name.appimage.

It's completely portable and can easily be run from a usb or an unprivileged user or a limited fresh install.

**Comment by NullArray** [comment]
I am familiar with AppImage. When i wrote my PowerShell installer for *Nix OS' i came across an AppImage release for PowerShell-Core. It's a lot like a stand-alone binary. And while it's true that it's easy to deploy something in that manner we also have Docker support. 

If we're going to do something like this we should categorize it as a binary release. I'll look into it.
