### ISSUE TITLE
Bug of AutoSploit execution

### ISSUE THREAD

**Issue by jkyumun** [NullArray/AutoSploit#41]
I have found an error during the execution of AutoSploit .
The error is as shown below.

C:\GitHub\AutoSploit>python autosploit.py
Traceback (most recent call last):
  File "autosploit.py", line 11, in <module>
    from blessings import Terminal
  File "C:\Python27\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "C:\Python27\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

C:\GitHub\AutoSploit>

My machine configuration is as below.
OS version : Windows 10 Home 64bit,
Python version : python-2.7.14 [C:\Python27]
Metasploit Framework version : Metasploit Framework-latest [C:\metasploit-framework]
Cloned AutoSploit : C:\GitHub\AutoSploit
Windows Defender : Disabled

Could someone can help me with this error?
Regards,

**Comment by Ekultek** [comment]
That’s not a bug, python doesn’t come with curses on Windows. https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses you probably shouldn’t be running this via windows anyways.

**Comment by NullArray** [comment]
Yeah, AutoSploit is not supported on Windows.

**Comment by jkyumun** [comment]
Thanks for your advice.
Is AutoSploit  supported on Kali Linux virtual machine ??
Looking forward to hearing soon.
Regards,

**Comment by jkyumun** [comment]
Thanks for your advice.
Is AutoSploit supported on Kali Linux virtual machine ??
Looking forward to hearing soon.
Regards,

2018-02-14 14:28 GMT+09:00 NullArray <notifications@github.com>:

**Comment by NullArray** [comment]
Yeah, it should work on Kali Linux.

**Comment by NullArray** [comment]
Make sure you configure your VM's network settings properly though, for any potential back connections coming your way from Reverse TCP Shells and such. The connections coming back to you will need to be properly forwarded to your VM.
