### ISSUE TITLE
Shodan API

### ISSUE THREAD

**Issue by djobes31770** [NullArray/AutoSploit#43]
I have run shodan init and even tried to put the api key into the autosploit.py file but i still get the following error:

------------------------------------------------------

[+]Please stand by while results are being collected...

[!]Critical. An error was raised with the following error message.

Invalid API key

**Comment by Ekultek** [comment]
Make sure your API key doesn’t have white space after it.

**Comment by NullArray** [comment]
Yeah no whites paces or single quotes `'` you just need to paste the alphanumeric key.
