### ISSUE TITLE
no arguments have been passed----02

### ISSUE THREAD

**Issue by CXXHK** [NullArray/AutoSploit#577]
![image](https://user-images.githubusercontent.com/45706420/54595238-32761180-4a6d-11e9-897c-ccf285541de1.png)
![image](https://user-images.githubusercontent.com/45706420/54595732-2b9bce80-4a6e-11e9-93a2-b944e6d85e99.png)

Hello, continue to ask you questions.
Why did you jump directly after selecting the mode, and there is no interface in your tutorial.
After entering the API, why can't I get this interface?
Thank you for your reply!

**Comment by Ekultek** [comment]
I'm not entirely sure what you're saying? Are you asking why do we drop you into a terminal when you don't pass any arguments to the program itself?
