### ISSUE TITLE
german README: hyperlinks refer to english version

### ISSUE THREAD

**Issue by techn0punk** [NullArray/AutoSploit#580]
# /AutoSploit/.github/.translations/README-de.md
In section **Hilfreiche Links** _(UsefulLinks)_ the links point to english README.md in root directory.

**Example** _(line 15)_ :
```
 - [Abhängigkeiten](https://github.com/NullArray/AutoSploit#dependencies)
                                                           ^~~~~ 
```

**but it should be like:**
```
 - [Abhängigkeiten](https://github.com/NullArray/AutoSploit/.github/.translations/README-de.md#abhängigkeiten)
```

**Comment by Ekultek** [comment]
pull request

**Comment by NullArray** [comment]
> pull request

Yeah, if you know what the issue is and it's easy to resolve a Pull Request would be greatly appreciated.
