### ISSUE TITLE
french README: hyperlinks refer to incorrect location

### ISSUE THREAD

**Issue by techn0punk** [NullArray/AutoSploit#581]
# /AutoSploit/.github/.translations/README-fr.md
In section **Liens utiles** _(UsefulLinks)_ the links point to repository root. But translations are in /AutoSploit/.github/.translations/

**Example** _(line 15)_ :
```
 - [Installation](https://github.com/NullArray/AutoSploit/README-fr.md#Installation)
                                                          ^~~~~ 
```

**but it should be like:**
```
 - [Installation](https://github.com/NullArray/AutoSploit/.github/.translations/README-fr.md#Installation)
```

**Comment by Ekultek** [comment]
Would you be able to add this as a pull request?
