### ISSUE TITLE
isssue

### ISSUE THREAD

**Issue by therapyuser** [NullArray/AutoSploit#596]
debian-custom
clone/downloaded zip
 
[-] no arguments have been passed, dropping into terminal session. to get help type `help` to quit type `exit/quit` to get help on a specific command type `command help`

i get this right after i enter shodan and censys api token and id
autosploit 3.0

**Comment by Ekultek** [comment]
Whats the problem?

**Comment by therapyuser** [comment]
is that normal to say no arguements have been passed?

**Comment by Ekultek** [comment]
@therapyuser yes it is, it's just indicating that no arguments were parsed at run time, I guess it is a little misleading of a message. I'll go ahead and change it to `no arguments have been parsed during runtime dropping into terminal session`

**Comment by Ekultek** [comment]
<img width="1478" alt="noArgumentsParsed" src="https://user-images.githubusercontent.com/14183473/55079133-97cb9300-5069-11e9-914b-1a78551e47ab.png">

How's that?

**Comment by Ekultek** [comment]
here you go it's been changed here: https://github.com/NullArray/AutoSploit/commit/a7d9ce5a1e7a3b384281c53cd235830016f1ca87, look for it in the next release

**Comment by therapyuser** [comment]
Sweet thank you so much also awesome work
