### ISSUE TITLE
[Request] zoomeye.org

### ISSUE THREAD

**Issue by zero77** [NullArray/AutoSploit#64]
Can you please add support for https://www.zoomeye.org/ alongside Shodan.io.
Thanks

**Comment by Ekultek** [comment]
Depends on what the significance of that site is? We're working on implementing Censys.io [already](https://github.com/NullArray/AutoSploit/tree/dev-beta)

**Comment by zero77** [comment]
It generally seems to have quite a lot of results and gives users less restrictions than Shodan.

**Comment by Ekultek** [comment]
What’s the difference between it and Censys?

**Comment by zero77** [comment]
There seem to be more results in zoomeye than censys, its like google vs yahoo vs duckduckgo each returns different results.

For example, when you search ssh zoomeye has 66,062,549 results and censys has 10,828,406 results.

**Comment by Ekultek** [comment]
@NullArray whatcha think?

**Comment by kimocoder** [comment]
It should be a good solution to search within all of them, with an option on which one to use of them.

**Comment by Ekultek** [comment]
@kimocoder that’s a lot of requesting though and a lot of potential error handling

**Comment by Ekultek** [comment]
I think it’s a pretty decent idea though. And the API looks pretty friendly https://www.zoomeye.org/api

**Comment by kimocoder** [comment]
Sure would be. May out it on the TODO list for later, handling all those different API's sure would bring some  work.

**Comment by Ekultek** [comment]
Connecting to the API and writing the code for them isn’t the problem. The error handling will be the issue because every API allows a certain amount at a time. So depending on what their limit is and how the connection works, it could be an issue. Other then that, the coding part is easy.

**Comment by NullArray** [comment]
I think it's a good idea to add Zoomeye. The more hosts we can gather the better. Getting AutoSploit set up to support this shouldn't be hard at all. 

So the documentation gives this as an example with the `curl` utility.

```
curl -X GET 'https://api.zoomeye.org/host/search?query=port:21%20city:beijing&page=1&facet=app,os' \
-H "Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5..."
```
We can work it in much the same way by using the PycURL library and StringIO. We could even parse the results as JSON in much the same way i did in [my Mimir tool](https://github.com/NullArray/Mimir/blob/master/mimir.py#L129).

The benefit of parsing the results as JSON would be the fact that by doing so we can pass the host list as a dict to the `msfrpc` service.

**Comment by Ekultek** [comment]
@NullArray we don’t need to add another requirement. We just use requests;

```
requests.get(<api-link>, params={“Authorization”: “<key>”})
```

**Comment by NullArray** [comment]
I don't mind either way.

**Comment by Ekultek** [comment]
@NullArray I'm working on it right now

**Comment by NullArray** [comment]
Appreciate it (n_n")

**Comment by Ekultek** [comment]
@zero77 @kimocoder @NullArray 

You have to use a phone number to get an API token on zoomeye. Are we sure we want this implemented?

**Comment by kimocoder** [comment]
Can't really answer to that at the moment, don't got time to look at zoomeye's stuff until this weekend.

**Comment by Ekultek** [comment]
Done just need to implement it into the flow

**Comment by NullArray** [comment]
We've plucked some auth_tokens out of the aether, which will be encoded and incorporated as default authentication for all autosploit users. So no phone numbers required.

**Comment by Ekultek** [comment]
@NullArray #hacktheworld

**Comment by NullArray** [comment]
![alt text](https://i.warosu.org/data/g/img/0497/70/1439959722680.jpg)

**Comment by zero77** [comment]
@Ekultek @NullArray 
Thanks
