### ISSUE TITLE
[!] Unhandled Option.

### ISSUE THREAD

**Issue by sky305** [NullArray/AutoSploit#68]
getting while trying to gather hosts from shodan.  not searching, not creating hosts.txt

**Comment by Ekultek** [comment]
Did you download the master branch?

**Comment by Ekultek** [comment]
If not, download the master branch, not dev-beta and try again.

**Comment by sky305** [comment]
dev-beta, should i merge with master ?

**Comment by Ekultek** [comment]
No, you should download master and leave the `beta` version alone
