### ISSUE TITLE
[Community] Installation methods

### ISSUE THREAD

**Issue by Ekultek** [NullArray/AutoSploit#82]
We have been discussing some installation methods to fix our rollover issue (issue #55) and have come up with a potential solution, this will bring in a problem with installation though. So we as a team have decided to give this option to the community.

 - First option
Create a simple installation script that will do everything with a simple command line run something like `sudo bash configure.sh`
- Second option
Create a command that you can copy and paste that will do the installation for you something like:
```
sudo -s << EOF
git clone <LINK>
sudo pip2 install msgpack
cd msfrpc/python-msfrpc
python setup.py install
mkdir /opt
cd /opt
git clone autosploit
cd /opt/autosploit
pip2 install - r reqs.txt
EOF
```
 - Option three
Both.

Leave your comment here, you can also vote on our poll on [Twitter](https://twitter.com/Real__Vector/status/969359149581684736) or on our [Discord server](https://discord.gg/9BeeZQk)

Either way the configuration for the program will be done automatically, but how you want it to be done is up to you.

**Comment by thehappydinoa** [comment]
Check #85 for install.sh

**Comment by jesuiscamille** [comment]
How about replacing 
```sh
sudo -s << EOF 
... snip ...
EOF
```
by
```sh
sudo su
... snip ...
```
?

It would looks less complicated to begginers

**Comment by Ekultek** [comment]
@jesuiscamille Why am I worried about beginners? All you literally have to do is copy and paste the command. That's it.

**Comment by jesuiscamille** [comment]
@Ekultek I'm not searching for help, I'm trying to find areas where I can contribute :)

**Comment by Ekultek** [comment]
@jesuiscamille we really need translations of the README, so if you know any other languages and wanna translate it for us it would be greatly appreciated!

**Comment by jesuiscamille** [comment]
@Ekultek will look at it :+1: !

**Comment by Ekultek** [comment]
@jesuiscamille you're my hero!!!

**Comment by Ekultek** [comment]
@jesuiscamille remember to send the PR to the dev-beta branch and not master, thank you ahead of time!

**Comment by Ekultek** [comment]
Calling it! Both it is
