### ISSUE TITLE
The standard

### ISSUE THREAD

**Issue by menkar3** [NullArray/AutoSploit#90]
I think, it will be useful to add small programming style convention document for contributors.
Such as:
<ul>
<li>UpperCamelCase for classes and snake_case for functions
<li>Upper case for constants
<li><i>from foo import * </i> are forbidden. Import all the modules between parentheses.
</ul>
#optional
<ul>
<li>global variables are forbidden
<li>files longer than NUM lines are not allowed - try to manage your code between small modules.
<li>OOP is strongly recommended
</ul>
etc

**Comment by Ekultek** [comment]
I agree, need @NullArray’s approval for these kinds of things though

**Comment by Ekultek** [comment]
https://github.com/NullArray/AutoSploit/wiki/Development-information#contribution-standards
